<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frauddetection_v1.proto

namespace NewestIndustry\FDS;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>frauddetection_v1.CheckOrderRequest</code>
 */
class CheckOrderRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Request metadata
     *
     * Generated from protobuf field <code>.frauddetection_v1.Meta meta = 1;</code>
     */
    private $meta = null;
    /**
     * Order to check
     *
     * Generated from protobuf field <code>.frauddetection_v1.Order order = 2;</code>
     */
    private $order = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \NewestIndustry\FDS\Meta $meta
     *           Request metadata
     *     @type \NewestIndustry\FDS\Order $order
     *           Order to check
     * }
     */
    public function __construct($data = NULL) {
        \NewestIndustry\GPBMetadata\FrauddetectionV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Request metadata
     *
     * Generated from protobuf field <code>.frauddetection_v1.Meta meta = 1;</code>
     * @return \NewestIndustry\FDS\Meta
     */
    public function getMeta()
    {
        return $this->meta;
    }

    /**
     * Request metadata
     *
     * Generated from protobuf field <code>.frauddetection_v1.Meta meta = 1;</code>
     * @param \NewestIndustry\FDS\Meta $var
     * @return $this
     */
    public function setMeta($var)
    {
        GPBUtil::checkMessage($var, \NewestIndustry\FDS\Meta::class);
        $this->meta = $var;

        return $this;
    }

    /**
     * Order to check
     *
     * Generated from protobuf field <code>.frauddetection_v1.Order order = 2;</code>
     * @return \NewestIndustry\FDS\Order
     */
    public function getOrder()
    {
        return $this->order;
    }

    /**
     * Order to check
     *
     * Generated from protobuf field <code>.frauddetection_v1.Order order = 2;</code>
     * @param \NewestIndustry\FDS\Order $var
     * @return $this
     */
    public function setOrder($var)
    {
        GPBUtil::checkMessage($var, \NewestIndustry\FDS\Order::class);
        $this->order = $var;

        return $this;
    }

}

