<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/frauddetection_v1.proto

namespace NewestIndustry\FDS;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>frauddetection_v1.CheckOrderResponse</code>
 */
class CheckOrderResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Response metadata
     *
     * Generated from protobuf field <code>.frauddetection_v1.Meta meta = 1;</code>
     */
    private $meta = null;
    /**
     * Fraud Probability Score will be between 0 and 1, where 0 is most probable to be fraud and 1 is least probable.
     *
     * Generated from protobuf field <code>double score = 2;</code>
     */
    private $score = 0.0;
    /**
     * Success will hold the success status of the checks. This will tell if a critical validation error was encountered.
     * (e.g. A check does an API call and the API is unreachable. In this case we could not complete validation so the
     * score will not be representable).
     *
     * Generated from protobuf field <code>bool success = 3;</code>
     */
    private $success = false;
    /**
     * Errors will contain a collection of errors thrown during calculation (e.g. Data validation)
     *
     * Generated from protobuf field <code>repeated .frauddetection_v1.CheckError errors = 4;</code>
     */
    private $errors;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \NewestIndustry\FDS\Meta $meta
     *           Response metadata
     *     @type float $score
     *           Fraud Probability Score will be between 0 and 1, where 0 is most probable to be fraud and 1 is least probable.
     *     @type bool $success
     *           Success will hold the success status of the checks. This will tell if a critical validation error was encountered.
     *           (e.g. A check does an API call and the API is unreachable. In this case we could not complete validation so the
     *           score will not be representable).
     *     @type \NewestIndustry\FDS\CheckError[]|\Google\Protobuf\Internal\RepeatedField $errors
     *           Errors will contain a collection of errors thrown during calculation (e.g. Data validation)
     * }
     */
    public function __construct($data = NULL) {
        \NewestIndustry\GPBMetadata\FrauddetectionV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Response metadata
     *
     * Generated from protobuf field <code>.frauddetection_v1.Meta meta = 1;</code>
     * @return \NewestIndustry\FDS\Meta
     */
    public function getMeta()
    {
        return $this->meta;
    }

    /**
     * Response metadata
     *
     * Generated from protobuf field <code>.frauddetection_v1.Meta meta = 1;</code>
     * @param \NewestIndustry\FDS\Meta $var
     * @return $this
     */
    public function setMeta($var)
    {
        GPBUtil::checkMessage($var, \NewestIndustry\FDS\Meta::class);
        $this->meta = $var;

        return $this;
    }

    /**
     * Fraud Probability Score will be between 0 and 1, where 0 is most probable to be fraud and 1 is least probable.
     *
     * Generated from protobuf field <code>double score = 2;</code>
     * @return float
     */
    public function getScore()
    {
        return $this->score;
    }

    /**
     * Fraud Probability Score will be between 0 and 1, where 0 is most probable to be fraud and 1 is least probable.
     *
     * Generated from protobuf field <code>double score = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setScore($var)
    {
        GPBUtil::checkDouble($var);
        $this->score = $var;

        return $this;
    }

    /**
     * Success will hold the success status of the checks. This will tell if a critical validation error was encountered.
     * (e.g. A check does an API call and the API is unreachable. In this case we could not complete validation so the
     * score will not be representable).
     *
     * Generated from protobuf field <code>bool success = 3;</code>
     * @return bool
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * Success will hold the success status of the checks. This will tell if a critical validation error was encountered.
     * (e.g. A check does an API call and the API is unreachable. In this case we could not complete validation so the
     * score will not be representable).
     *
     * Generated from protobuf field <code>bool success = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->success = $var;

        return $this;
    }

    /**
     * Errors will contain a collection of errors thrown during calculation (e.g. Data validation)
     *
     * Generated from protobuf field <code>repeated .frauddetection_v1.CheckError errors = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getErrors()
    {
        return $this->errors;
    }

    /**
     * Errors will contain a collection of errors thrown during calculation (e.g. Data validation)
     *
     * Generated from protobuf field <code>repeated .frauddetection_v1.CheckError errors = 4;</code>
     * @param \NewestIndustry\FDS\CheckError[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setErrors($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \NewestIndustry\FDS\CheckError::class);
        $this->errors = $arr;

        return $this;
    }

}

