<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frauddetection_v1.proto

namespace NewestIndustry\FDS;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>frauddetection_v1.Customer</code>
 */
class Customer extends \Google\Protobuf\Internal\Message
{
    /**
     * Customer ID
     *
     * Generated from protobuf field <code>string id = 1;</code>
     */
    private $id = '';
    /**
     * Customer entity (either business or consumer)"
     *
     * Generated from protobuf field <code>string entity = 2;</code>
     */
    private $entity = '';
    /**
     * Name of customer
     *
     * Generated from protobuf field <code>string name = 3;</code>
     */
    private $name = '';
    /**
     * Chamber of Commerce ID (eg. in NLD this is the KVK Nummer)
     *
     * Generated from protobuf field <code>string coc_id = 4;</code>
     */
    private $coc_id = '';
    /**
     * Customer address
     *
     * Generated from protobuf field <code>.frauddetection_v1.Address address = 5;</code>
     */
    private $address = null;
    /**
     * Customer phone number (using E.164)
     *
     * Generated from protobuf field <code>string phone = 6;</code>
     */
    private $phone = '';
    /**
     * Customer email address
     *
     * Generated from protobuf field <code>string email = 7;</code>
     */
    private $email = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           Customer ID
     *     @type string $entity
     *           Customer entity (either business or consumer)"
     *     @type string $name
     *           Name of customer
     *     @type string $coc_id
     *           Chamber of Commerce ID (eg. in NLD this is the KVK Nummer)
     *     @type \NewestIndustry\FDS\Address $address
     *           Customer address
     *     @type string $phone
     *           Customer phone number (using E.164)
     *     @type string $email
     *           Customer email address
     * }
     */
    public function __construct($data = NULL) {
        \NewestIndustry\GPBMetadata\FrauddetectionV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Customer ID
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Customer ID
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Customer entity (either business or consumer)"
     *
     * Generated from protobuf field <code>string entity = 2;</code>
     * @return string
     */
    public function getEntity()
    {
        return $this->entity;
    }

    /**
     * Customer entity (either business or consumer)"
     *
     * Generated from protobuf field <code>string entity = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEntity($var)
    {
        GPBUtil::checkString($var, True);
        $this->entity = $var;

        return $this;
    }

    /**
     * Name of customer
     *
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Name of customer
     *
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Chamber of Commerce ID (eg. in NLD this is the KVK Nummer)
     *
     * Generated from protobuf field <code>string coc_id = 4;</code>
     * @return string
     */
    public function getCocId()
    {
        return $this->coc_id;
    }

    /**
     * Chamber of Commerce ID (eg. in NLD this is the KVK Nummer)
     *
     * Generated from protobuf field <code>string coc_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCocId($var)
    {
        GPBUtil::checkString($var, True);
        $this->coc_id = $var;

        return $this;
    }

    /**
     * Customer address
     *
     * Generated from protobuf field <code>.frauddetection_v1.Address address = 5;</code>
     * @return \NewestIndustry\FDS\Address
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Customer address
     *
     * Generated from protobuf field <code>.frauddetection_v1.Address address = 5;</code>
     * @param \NewestIndustry\FDS\Address $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkMessage($var, \NewestIndustry\FDS\Address::class);
        $this->address = $var;

        return $this;
    }

    /**
     * Customer phone number (using E.164)
     *
     * Generated from protobuf field <code>string phone = 6;</code>
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * Customer phone number (using E.164)
     *
     * Generated from protobuf field <code>string phone = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone = $var;

        return $this;
    }

    /**
     * Customer email address
     *
     * Generated from protobuf field <code>string email = 7;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Customer email address
     *
     * Generated from protobuf field <code>string email = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

}

