<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/frauddetection_v1.proto

namespace NewestIndustry\FDS;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>frauddetection_v1.MerchantSaveResponse</code>
 */
class MerchantSaveResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.frauddetection_v1.Merchant merchant = 1;</code>
     */
    private $merchant = null;
    /**
     * Errors will contain a collection of errors thrown during calculation (e.g. Data validation)
     *
     * Generated from protobuf field <code>repeated .frauddetection_v1.ValidationError validation_errors = 2;</code>
     */
    private $validation_errors;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \NewestIndustry\FDS\Merchant $merchant
     *     @type \NewestIndustry\FDS\ValidationError[]|\Google\Protobuf\Internal\RepeatedField $validation_errors
     *           Errors will contain a collection of errors thrown during calculation (e.g. Data validation)
     * }
     */
    public function __construct($data = NULL) {
        \NewestIndustry\GPBMetadata\FrauddetectionV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.frauddetection_v1.Merchant merchant = 1;</code>
     * @return \NewestIndustry\FDS\Merchant
     */
    public function getMerchant()
    {
        return $this->merchant;
    }

    /**
     * Generated from protobuf field <code>.frauddetection_v1.Merchant merchant = 1;</code>
     * @param \NewestIndustry\FDS\Merchant $var
     * @return $this
     */
    public function setMerchant($var)
    {
        GPBUtil::checkMessage($var, \NewestIndustry\FDS\Merchant::class);
        $this->merchant = $var;

        return $this;
    }

    /**
     * Errors will contain a collection of errors thrown during calculation (e.g. Data validation)
     *
     * Generated from protobuf field <code>repeated .frauddetection_v1.ValidationError validation_errors = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getValidationErrors()
    {
        return $this->validation_errors;
    }

    /**
     * Errors will contain a collection of errors thrown during calculation (e.g. Data validation)
     *
     * Generated from protobuf field <code>repeated .frauddetection_v1.ValidationError validation_errors = 2;</code>
     * @param \NewestIndustry\FDS\ValidationError[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setValidationErrors($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \NewestIndustry\FDS\ValidationError::class);
        $this->validation_errors = $arr;

        return $this;
    }

}

