<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/frauddetection_v1.proto

namespace NewestIndustry\FDS;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>frauddetection_v1.Order</code>
 */
class Order extends \Google\Protobuf\Internal\Message
{
    /**
     * Time order is placed
     *
     * Generated from protobuf field <code>.frauddetection_v1.Timestamp time = 1;</code>
     */
    private $time = null;
    /**
     * Order ID
     *
     * Generated from protobuf field <code>string id = 2;</code>
     */
    private $id = '';
    /**
     * Merchant handling the order
     *
     * Generated from protobuf field <code>.frauddetection_v1.Merchant merchant = 3;</code>
     */
    private $merchant = null;
    /**
     * Customer
     *
     * Generated from protobuf field <code>.frauddetection_v1.Customer customer = 4;</code>
     */
    private $customer = null;
    /**
     * Payment details and method
     *
     * Generated from protobuf field <code>.frauddetection_v1.Payment payment = 5;</code>
     */
    private $payment = null;
    /**
     * Total order price
     *
     * Generated from protobuf field <code>int64 amount = 6;</code>
     */
    private $amount = 0;
    /**
     * How much discount is given on this order
     *
     * Generated from protobuf field <code>int64 discount = 7;</code>
     */
    private $discount = 0;
    /**
     * Shipment details
     *
     * Generated from protobuf field <code>.frauddetection_v1.Shipment shipment = 8;</code>
     */
    private $shipment = null;
    /**
     * Orderlines (products bought)
     *
     * Generated from protobuf field <code>repeated .frauddetection_v1.OrderLine orderline = 9;</code>
     */
    private $orderline;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \NewestIndustry\FDS\Timestamp $time
     *           Time order is placed
     *     @type string $id
     *           Order ID
     *     @type \NewestIndustry\FDS\Merchant $merchant
     *           Merchant handling the order
     *     @type \NewestIndustry\FDS\Customer $customer
     *           Customer
     *     @type \NewestIndustry\FDS\Payment $payment
     *           Payment details and method
     *     @type int|string $amount
     *           Total order price
     *     @type int|string $discount
     *           How much discount is given on this order
     *     @type \NewestIndustry\FDS\Shipment $shipment
     *           Shipment details
     *     @type \NewestIndustry\FDS\OrderLine[]|\Google\Protobuf\Internal\RepeatedField $orderline
     *           Orderlines (products bought)
     * }
     */
    public function __construct($data = NULL) {
        \NewestIndustry\GPBMetadata\FrauddetectionV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Time order is placed
     *
     * Generated from protobuf field <code>.frauddetection_v1.Timestamp time = 1;</code>
     * @return \NewestIndustry\FDS\Timestamp
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * Time order is placed
     *
     * Generated from protobuf field <code>.frauddetection_v1.Timestamp time = 1;</code>
     * @param \NewestIndustry\FDS\Timestamp $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkMessage($var, \NewestIndustry\FDS\Timestamp::class);
        $this->time = $var;

        return $this;
    }

    /**
     * Order ID
     *
     * Generated from protobuf field <code>string id = 2;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Order ID
     *
     * Generated from protobuf field <code>string id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Merchant handling the order
     *
     * Generated from protobuf field <code>.frauddetection_v1.Merchant merchant = 3;</code>
     * @return \NewestIndustry\FDS\Merchant
     */
    public function getMerchant()
    {
        return $this->merchant;
    }

    /**
     * Merchant handling the order
     *
     * Generated from protobuf field <code>.frauddetection_v1.Merchant merchant = 3;</code>
     * @param \NewestIndustry\FDS\Merchant $var
     * @return $this
     */
    public function setMerchant($var)
    {
        GPBUtil::checkMessage($var, \NewestIndustry\FDS\Merchant::class);
        $this->merchant = $var;

        return $this;
    }

    /**
     * Customer
     *
     * Generated from protobuf field <code>.frauddetection_v1.Customer customer = 4;</code>
     * @return \NewestIndustry\FDS\Customer
     */
    public function getCustomer()
    {
        return $this->customer;
    }

    /**
     * Customer
     *
     * Generated from protobuf field <code>.frauddetection_v1.Customer customer = 4;</code>
     * @param \NewestIndustry\FDS\Customer $var
     * @return $this
     */
    public function setCustomer($var)
    {
        GPBUtil::checkMessage($var, \NewestIndustry\FDS\Customer::class);
        $this->customer = $var;

        return $this;
    }

    /**
     * Payment details and method
     *
     * Generated from protobuf field <code>.frauddetection_v1.Payment payment = 5;</code>
     * @return \NewestIndustry\FDS\Payment
     */
    public function getPayment()
    {
        return $this->payment;
    }

    /**
     * Payment details and method
     *
     * Generated from protobuf field <code>.frauddetection_v1.Payment payment = 5;</code>
     * @param \NewestIndustry\FDS\Payment $var
     * @return $this
     */
    public function setPayment($var)
    {
        GPBUtil::checkMessage($var, \NewestIndustry\FDS\Payment::class);
        $this->payment = $var;

        return $this;
    }

    /**
     * Total order price
     *
     * Generated from protobuf field <code>int64 amount = 6;</code>
     * @return int|string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Total order price
     *
     * Generated from protobuf field <code>int64 amount = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * How much discount is given on this order
     *
     * Generated from protobuf field <code>int64 discount = 7;</code>
     * @return int|string
     */
    public function getDiscount()
    {
        return $this->discount;
    }

    /**
     * How much discount is given on this order
     *
     * Generated from protobuf field <code>int64 discount = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDiscount($var)
    {
        GPBUtil::checkInt64($var);
        $this->discount = $var;

        return $this;
    }

    /**
     * Shipment details
     *
     * Generated from protobuf field <code>.frauddetection_v1.Shipment shipment = 8;</code>
     * @return \NewestIndustry\FDS\Shipment
     */
    public function getShipment()
    {
        return $this->shipment;
    }

    /**
     * Shipment details
     *
     * Generated from protobuf field <code>.frauddetection_v1.Shipment shipment = 8;</code>
     * @param \NewestIndustry\FDS\Shipment $var
     * @return $this
     */
    public function setShipment($var)
    {
        GPBUtil::checkMessage($var, \NewestIndustry\FDS\Shipment::class);
        $this->shipment = $var;

        return $this;
    }

    /**
     * Orderlines (products bought)
     *
     * Generated from protobuf field <code>repeated .frauddetection_v1.OrderLine orderline = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOrderline()
    {
        return $this->orderline;
    }

    /**
     * Orderlines (products bought)
     *
     * Generated from protobuf field <code>repeated .frauddetection_v1.OrderLine orderline = 9;</code>
     * @param \NewestIndustry\FDS\OrderLine[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOrderline($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \NewestIndustry\FDS\OrderLine::class);
        $this->orderline = $arr;

        return $this;
    }

}

