<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frauddetection_v1.proto

namespace NewestIndustry\FDS;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>frauddetection_v1.Payment</code>
 */
class Payment extends \Google\Protobuf\Internal\Message
{
    /**
     * Amount payed
     *
     * Generated from protobuf field <code>int64 amount = 1;</code>
     */
    private $amount = 0;
    /**
     * Enumerated payment method (cc, ideal, other)
     *
     * Generated from protobuf field <code>string method = 2;</code>
     */
    private $method = '';
    /**
     * Is payment provided upfront (false) or after the order is received (true)
     *
     * Generated from protobuf field <code>bool postpay = 3;</code>
     */
    private $postpay = false;
    /**
     * Currency symbol
     *
     * Generated from protobuf field <code>string currency = 4;</code>
     */
    private $currency = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $amount
     *           Amount payed
     *     @type string $method
     *           Enumerated payment method (cc, ideal, other)
     *     @type bool $postpay
     *           Is payment provided upfront (false) or after the order is received (true)
     *     @type string $currency
     *           Currency symbol
     * }
     */
    public function __construct($data = NULL) {
        \NewestIndustry\GPBMetadata\FrauddetectionV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Amount payed
     *
     * Generated from protobuf field <code>int64 amount = 1;</code>
     * @return int|string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Amount payed
     *
     * Generated from protobuf field <code>int64 amount = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Enumerated payment method (cc, ideal, other)
     *
     * Generated from protobuf field <code>string method = 2;</code>
     * @return string
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * Enumerated payment method (cc, ideal, other)
     *
     * Generated from protobuf field <code>string method = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMethod($var)
    {
        GPBUtil::checkString($var, True);
        $this->method = $var;

        return $this;
    }

    /**
     * Is payment provided upfront (false) or after the order is received (true)
     *
     * Generated from protobuf field <code>bool postpay = 3;</code>
     * @return bool
     */
    public function getPostpay()
    {
        return $this->postpay;
    }

    /**
     * Is payment provided upfront (false) or after the order is received (true)
     *
     * Generated from protobuf field <code>bool postpay = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setPostpay($var)
    {
        GPBUtil::checkBool($var);
        $this->postpay = $var;

        return $this;
    }

    /**
     * Currency symbol
     *
     * Generated from protobuf field <code>string currency = 4;</code>
     * @return string
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * Currency symbol
     *
     * Generated from protobuf field <code>string currency = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrency($var)
    {
        GPBUtil::checkString($var, True);
        $this->currency = $var;

        return $this;
    }

}

