<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/frauddetection_v1.proto

namespace NewestIndustry\FDS;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>frauddetection_v1.Shipment</code>
 */
class Shipment extends \Google\Protobuf\Internal\Message
{
    /**
     * Shipping address
     *
     * Generated from protobuf field <code>.frauddetection_v1.Address address = 1;</code>
     */
    private $address = null;
    /**
     * Carrier identifier
     *
     * Generated from protobuf field <code>string carrier = 2;</code>
     */
    private $carrier = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \NewestIndustry\FDS\Address $address
     *           Shipping address
     *     @type string $carrier
     *           Carrier identifier
     * }
     */
    public function __construct($data = NULL) {
        \NewestIndustry\GPBMetadata\FrauddetectionV1::initOnce();
        parent::__construct($data);
    }

    /**
     * Shipping address
     *
     * Generated from protobuf field <code>.frauddetection_v1.Address address = 1;</code>
     * @return \NewestIndustry\FDS\Address
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Shipping address
     *
     * Generated from protobuf field <code>.frauddetection_v1.Address address = 1;</code>
     * @param \NewestIndustry\FDS\Address $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkMessage($var, \NewestIndustry\FDS\Address::class);
        $this->address = $var;

        return $this;
    }

    /**
     * Carrier identifier
     *
     * Generated from protobuf field <code>string carrier = 2;</code>
     * @return string
     */
    public function getCarrier()
    {
        return $this->carrier;
    }

    /**
     * Carrier identifier
     *
     * Generated from protobuf field <code>string carrier = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCarrier($var)
    {
        GPBUtil::checkString($var, True);
        $this->carrier = $var;

        return $this;
    }

}

